### ISSUE TITLE
Inicio 2-Criar um template

### ISSUE THREAD

**Issue by Rafalexandre-code** [fabsoftwareitp/sge-laravel#32]
será nescessário cadastrar um template para conseguirmos trabalhar no laravel, depois criar um evento

**Comment by Rafalexandre-code** [comment]
Primeiro vc deve cadastrar um usuario para vermos oque o usuario vê e quais problemas ele possivelmente pode ter, depois na pasta /database/seeds/create_admin.php para se ter acesso ao email e senha da parte de administrador do projeto para criarmos templates e eventos

**Comment by danilocbueno** [comment]
Verificar o template padrão que provavelmente não existe.
Cadastrar um novo template e ver se está verificando corretamente;
